:toc:
:sectnums:
:toclevels: 5
:sectnumlevels: 5
:showcomments:
:xrefstyle: short
:icons: font
:source-highlighter: coderay
:tick: &#x2714;
:pound: &#xA3;

= C# Print Formats

To those of us who many years ago learned `printf`, C# print formats can be hard to remember. This is, partly of course, due to the fact that
our brains have atrophied since that golden era.

Here is a simple guide.

== Interpolated strings

C# was the first language to support the concept of interpolated strings - many other languages have followed this lead. Before C# 6, you would need to print
a string as follows:

[source,csharp]
----
private static void Main()
{
    var entity = "world";
    Console.WriteLine("Hello {0}", entity);
}
----

Now the same code can be written as

[source,csharp]
----
private static void Main()
{
    var entity = "world";
    Console.WriteLine($"Hello {entity}");
}
----

This is a lot more readable and allows a simple way of concatenating multiple strings. You don't have to print the result: you can use the value 
returned (which is of type `System.String` aka `string`). For example:

[source,csharp]
----
private static void Main()
{
    var entity = "world";
    var greeting = "Hello";
    var phrase = $"{greeting} {entity}";
    Console.WriteLine(phrase);
}
----

== Printing integers

=== Leading Spaces

To "right-justify" an integer in a field - that is to pad the left of the integer with spaces, simply add a comma then a second integer denoting the field width:

[source,csharp]
----
var i = 1234;
var j = 5576788;
var i2 = 8;
Console.WriteLine($"{i,5}|{j}");
Console.WriteLine($"{i2,5}|{j}");
----

The result is:

----
 1234|5576788
    8|5576788
----

=== Trailing spaces

To add **trailing** spaces - i.e. spaces to the right of the integer, use a **negative** number as the print format:

[source,csharp]
----
var i = 1234;
var j = 5576788;
var i2 = 8;
Console.WriteLine($"{i,-5}|{j}");
Console.WriteLine($"{i2,-5}|{j}");
----

The result is:

----
1234 |5576788
8    |5576788
----

=== Leading zeros

To print an integer with leading zeros **in decimal**, use a capital D:

[source,csharp]
----
var i = 1234;
Console.WriteLine($"{i:D8}");
----

The result is:

----
00001234
----

=== Leading zeroes and leading spaces

You can also print in a fixed width field with leading zeros. So, for example, to print right-justified in a ten-character field with a total of four digits:

[source,csharp]
----
var i = 123;
Console.WriteLine($"{i,10:D4}");
----

The result is
----
      0123|
----

=== Hexadecimal

==== Upper case letters 'A'-'F'

To print an integer in hexadecimal, use a capital X instead of D:

[source,csharp]
----
var i = 123;
Console.WriteLine($"{i:X4}");
----

The result is 
----
007B
----

==== Lower case letters 'a'-'f'

To get lower case hex letters, use a lowercase x as the print format specifier instead of an upper case X.

=== Commas for thousands

Use the `n` print format specifier to get commas to separate numbers. Use n0 to get zero decimal places (obviously no dot either). 
This format can be used for the following types: `integer`, `float`, `double` and `decimal`.

[source,csharp]
----
var i = 9876123;
Console.WriteLine($"{i:n0}");

var d = 9876123.45;
Console.WriteLine($"{d:n}");

decimal money = 123456789.453M;
Console.WriteLine($"{money:n}");
Console.WriteLine($"{money:n0}");
Console.WriteLine($"{money:n5}");
----

The result is:
----
9,876,123
9,876,123.45
123,456,789.45
123,456,789
123,456,789.45300
----

**The number after the n is the number of decimal places**

=== Decimal places without commas

Use the `f` (fixed point) specifier:

[source,csharp]
----
var d = 123456.789;
Console.WriteLine($"{d:f2}");
----

The result is:

----
123456.79
----

**Note that the result is rounded**

== Internationalisation

In much of Europe, the three-digit separator is a space (NOT a comma). A decimal point is not used - a comma is used instead.

=== Setting the thread culture

If we set the current thread's culture to a European culture (e.g. French), we will see a comma instead of a decimal point and a 
space instead of a comma for the separator.

[source,csharp]
----
var d = 123456.789;
Console.WriteLine($"{d:n3}");

// set French culture:
Thread.CurrentThread.CurrentCulture = new CultureInfo("fr-FR");
Console.WriteLine($"{d:n3}");
----

The result is
----
123,456.789
123 456,789
----

=== Specifying a culture for `ToString()`

[source,csharp]
----
var inFrench = new CultureInfo("fr-FR");
var result = d.ToString("n3", inFrench);
Console.WriteLine(result);
----

The result is:

----
123 456,789
----

This is possible because `CultureInfo` implements the `IFormatProvider` interface.


=== Making a `FormattableString`

If you make a `FormattableString`, you can print it in any culture you specify:

[source,csharp]
----
var d = 123456.789;
FormattableString fs = $"{d:n3}";

// create some cultures:
var cultureStrings = new[] {"en-GB", "fr-FR", "cs-cz", "de-DE"}.ToList();
var cultures = cultureStrings.Select(x => new CultureInfo(x)).ToList();
cultures.ForEach(x => Console.WriteLine($"{fs.ToString(x)} - [{x.DisplayName}]"));
----

The result is:

----
123,456.789 - [English (United Kingdom)]
123 456,789 - [French (France)]
123 456,789 - [Czech (Czech Republic)]
123.456,789 - [German (Germany)]
----